import "./globals.css";
import { Patua_One } from "next/font/google";

const Patua = Patua_One({ subsets: ["latin"], display: "swap", weight: "400" });

export const metadata = {
  title: "Next13 Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Patua.className}>{children}</body>
    </html>
  );
}
